---
- name: add linuxuprising ppa key to apt-key
  apt_key: file=/root/linuxuprising_ppa.gpg
  sudo: yes

- name: linuxuprising java sources.list
  template: >
    src=linuxuprising-java.list.j2
    dest=/etc/apt/sources.list.d/linuxuprising-java.list
    force=no
  register: sources_list_result
  sudo: yes

- name: apt-get update
  apt: update_cache=true cache_valid_time=0
  when: sources_list_result.changed
  sudo: yes

- name: accept oracle license
  shell: >
    echo "oracle-java11-installer shared/accepted-oracle-license-v1-2
    select true" | debconf-set-selections
  sudo: yes
  changed_when: False

- name: accept oracle license
  shell: >
    echo "oracle-java11-installer shared/accepted-oracle-license-v1-2
    boolean true" | debconf-set-selections
  sudo: yes
  changed_when: False
