---
- name: write linuxuprising java ppa key to /root
  copy:
    src: linuxuprising_ppa.gpg
    dest: /root/linuxuprising_ppa.gpg
  sudo: yes

- name: add linuxuprising java ppa key to apt-key
  apt_key: file=/root/linuxuprising_ppa.gpg
  sudo: yes

- name: apt-get update
  apt: update_cache=true cache_valid_time=3600
  sudo: yes
